/* PhenologyPro — tests of Block 8: phenology on the series. */
(function () {
  const { check, section, near } = window.__t;
  const P = Pheno8;

  section('Bloque 8 · etapas por tiempo térmico y calibración');
  const flat = [];
  for (let y = 2020; y <= 2023; y++) for (let J = 1; J <= daysInYear(y); J++) { const d = fromDoy(y, J); const r = WxIO.emptyRow(y, d.m, d.d); r.tmax = 30; r.tmin = 20; r.prec = 0; flat.push(r); }
  const p = { method: 'average', base: 10, upper: 30, cutoff: 'horizontal', m: 4, d: 15 };
  const dd = Therm4.daily(flat, p);
  const stages = [{ code: '09', es: 'Emergencia', en: 'Emergence', gdd: 75 }, { code: '65', es: 'Floración', en: 'Flowering', gdd: 750 }, { code: '89', es: 'Madurez', en: 'Maturity', gdd: 1500 }];
  const res = P.stagesByYear(flat, dd, 4, 15, stages, p);
  check('stagesByYear: 4 años; a 15 °C·d/día la floración cae a los 50 días y la madurez a los 100', res.years.length === 4 && res.summary[1].median != null && near(res.summary[1].median, 50) && near(res.summary[2].median, 100) && res.summary.every(s => s.pReached === 1));
  check('stagesByYear: la floración (750 °C·d, cruzados al final del día 50) cae el día 49 tras la siembra', res.years.every(r => toISO(r.stages[1].date) === toISO(addDays({ y: r.y, m: 4, d: 15 }, 49))));
  check('stagesByYear: sin dispersión entre años idénticos (sd = 0, P20 = P80)', res.summary[2].sd === 0 && res.summary[2].p20 === res.summary[2].p80);
  /* calibration: observations generated by the model itself must return the same requirement */
  const obs = P.exampleObservations(res, ['65', '89'], 1).map(o => Object.assign({}, o));
  const exact = res.years.flatMap(r => [{ y: r.y, code: '65', date: r.stages[1].date }, { y: r.y, code: '89', date: r.stages[2].date }]);
  const cal = P.calibrate(flat, exact, p);
  check('calibrate: fechas exactas del modelo devuelven 750 y 1500 °C·d con CV 0', cal.stages.length === 2 && near(cal.stages.find(s => s.code === '65').mean, 750, 1e-6) && near(cal.stages.find(s => s.code === '89').mean, 1500, 1e-6) && cal.stages.every(s => s.cv === 0));
  check('calibrate: las observaciones con ruido dan medias cercanas y CV pequeño', (() => { const c = P.calibrate(flat, obs, p); return c.stages.every(s => s.cv != null && s.cv < 0.15) && Math.abs(c.stages.find(s => s.code === '89').mean - 1500) < 150; })());
  check('calibrate: la búsqueda de Arnold se hace con la etapa más observada y da una curva', cal.baseSearch && cal.baseSearch.code && cal.baseSearch.curve.length > 10 && cal.baseSearch.best != null);
  /* Arnold on a series whose "true" base is 10: build years with different temperatures so that only base 10 gives a constant thermal time */
  const varied = [];
  const tm = { 2020: 22, 2021: 25, 2022: 28, 2023: 19 };
  for (let y = 2020; y <= 2023; y++) for (let J = 1; J <= daysInYear(y); J++) { const d = fromDoy(y, J); const r = WxIO.emptyRow(y, d.m, d.d); r.tmax = tm[y] + 5; r.tmin = tm[y] - 5; r.prec = 0; varied.push(r); }
  const ddv = Therm4.daily(varied, p);
  const resV = P.stagesByYear(varied, ddv, 4, 15, [{ code: '89', es: 'M', en: 'M', gdd: 1200 }], p);
  const obsV = resV.years.map(r => ({ y: r.y, code: '89', date: r.stages[0].date }));
  const calV = P.calibrate(varied, obsV, p);
  check('Arnold: con años de distinta temperatura y una base verdadera de 10 °C, el mínimo del CV cae en 10 ± 0.5', calV.baseSearch && Math.abs(calV.baseSearch.best.base - 10) <= 0.5, calV.baseSearch && calV.baseSearch.best.base);
  check('parseObservations: año;etapa;fecha y siembra;etapa;fecha; líneas malas contadas', (() => { const r = P.parseObservations('# comentario\n2019; 65; 25/07/2019\n15/05/2020, 65, 02/08/2020\nbasura\n2021;89;20/10/2021'); return r.obs.length === 3 && r.bad.length === 1 && r.obs[1].sowing && r.obs[1].sowing.y === 2020 && r.obs[0].date.m === 7; })());

  section('Bloque 8 · frío invernal y fotoperiodo');
  const ex = WxIO.exampleSeries('cold', 5, false);
  const rows = WxIO.qc(ex.rows, {}).rows;
  const seasons = P.winterSeasons(rows, ex.site.lat, { startM: 11, endM: 2 });
  check('winterSeasons: 4 inviernos completos (nov–feb) de 5 años, 120 días cada uno', seasons.length === 4 && seasons.every(s => s.days === 120 || s.days === 121), seasons.map(s => s.days).join(','));
  check('winterSeasons: series diarias acumuladas monótonas (CP y horas) y totales coherentes', seasons.every(s => s.dCP.every((v, k) => k === 0 || v >= s.dCP[k - 1] - 1e-9) && s.dHours.every((v, k) => k === 0 || v >= s.dHours[k - 1]) && near(s.dCP[s.dCP.length - 1], s.cp, 1e-9) && near(s.dHours[s.dHours.length - 1], s.hours, 1e-9)));
  check('winterSeasons: el altiplano frío junta entre 30 y 90 porciones y más de 600 horas frío', seasons.every(s => s.cp > 30 && s.cp < 90 && s.hours > 600), seasons.map(s => s.cp.toFixed(0)).join(','));
  const sum = P.chillSummary(seasons, { unit: 'cp', value: 25 });
  check('chillSummary: medianas y percentiles; un requerimiento de 25 CP se cubre en todos los inviernos', sum.n === 4 && sum.cp.p20 <= sum.cp.median && sum.met.p === 1 && sum.met.dayMedian > 0, `${sum.cp.min.toFixed(1)}–${sum.cp.max.toFixed(1)} CP · p ${sum.met.p}`);
  check('chillSummary: un requerimiento imposible (500 CP) no se cubre nunca', P.chillSummary(seasons, { unit: 'cp', value: 500 }).met.p === 0);
  check('metOn: el día en que se cubre es el primero con la serie ≥ requerimiento', seasons.every(s => { const k = P.metOn(s, 'cp', 20); return k != null && s.dCP[k] >= 20 && (k === 0 || s.dCP[k - 1] < 20); }));
  const trop = WxIO.qc(WxIO.exampleSeries('tropical', 3, false).rows, {}).rows;
  const st = P.winterSeasons(trop, 19.2, { startM: 11, endM: 2 });
  check('trópico húmedo: casi sin porciones y unidades Utah negativas o casi nulas', st.length >= 1 && st.every(s => s.cp < 10 && s.utah < 100));
  const bloom = P.gdhToBloom(rows, ex.site.lat, seasons[0], P.metOn(seasons[0], 'cp', 40), 6000);
  check('gdhToBloom: tras cubrir el frío, 6 000 GDH se alcanzan en primavera con una fecha', bloom && bloom.day > 0 && bloom.gdh >= 6000 && bloom.date.m >= 1 && bloom.date.m <= 6, bloom && toISO(bloom.date));
  const ph = P.photoperiod(19.3);
  check('photoperiod: 365 días; máximo en junio, mínimo en diciembre; civil > geométrico', ph.days.length === 365 && ph.maxJ > 160 && ph.maxJ < 185 && ph.minJ > 340 && ph.days.every(x => x.civil > x.geometric));
  check('photoperiod: a 19.3° la diferencia entre el día más largo y el más corto es de ~2.5 h', ph.max - ph.min > 2 && ph.max - ph.min < 3);
  check('Help: 9 fichas del Bloque 8 y escala de calibración', Help.BLOCK_KEYS[8].length === 9 && Help.BLOCK_KEYS[8].every(k => Help.HELP[k]) && Help.band('calibration', 0.03).tone === 'good' && Help.band('calibration', 0.3).tone === 'bad');

  window.__t.finish();
})();
